name: Check In
on: pull_request_target
jobs:
  run-test:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: tianhaoz95-actions/dot-npmrc@v1.2.1
        with:
          org: "wowlink"
          token: ${{ secrets.GH_NPM_DOWNLOAD_TOKEN }}
      - run: npm install && npm test
  auto-approve:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.GH_REPO_ACCESS_TOKEN }}"
