name: Publish GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Generate GitHub registry credential file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PKG_DOWNLOAD_TOKEN }}" > .npmrc
          echo "@wowlink:registry=https://npm.pkg.github.com" >> .npmrc
          cat .npmrc
      - name: Install dependencies
        run: npm install
      - name: Build and push to GitHub pages branch
        run: npm run deploy
