name: Publish GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@wowlink"
      - name: Install dependencies
        run: npm install
      - name: Build and push to GitHub pages branch
        run: npm run deploy
