name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: tianhaoz95-actions/dot-npmrc@v1.2.1
        with:
          org: "wowlink"
          token: ${{ secrets.GH_NPM_DOWNLOAD_TOKEN }}
      - run: npm install
      - run: npm test
